### ISSUE TITLE
Library Branch not Found and Compile Errors

### ISSUE THREAD

**Issue by ab-tools** [OpenKNX/Examples#1]
Hello Mike,

first thanks a lot for taking the time to create these examples here!
That's really helpful to get you going.

I'm just trying to build the `PiPico_RP2040_Common` one, but it looks like that the branch `Flash_batchwrite` of the dependency
https://github.com/thelsing/knx#Flash_batchwrite
simply does not exist anymore.
Can the master branch be used instead?

Furthermore, the branch `modular` of the dependency
https://github.com/OpenKnx/OGM-Common#modular
still exists, but seems a bit outdated (> 100 commits behind master) in the meantime.
Any reason this particular branch was/is required or can just the master branch be used now?

However, no matter if I try with the master or the `modular` branch I do get some compile errors:
.pio\libdeps\pico\OGM-Common\src/OpenKNX.h:18:10: error: #error "OPENKNX_FLASH_SIZE is not defined"
.pio\libdeps\pico\OGM-Common\src/OpenKNX.h:14:10: error: #error "OPENKNX_FLASH_OFFSET is not defined"
.pio\libdeps\pico\OGM-Common\src/OpenKNX/defines.h:4:10: fatal error: versions.h: No such file or directory

I've checked the GitHub readme of the `OGM-Common` project, but looks like these two flash related options are not described there either:
https://github.com/OpenKnx/OGM-Common

Maybe you have an idea what I'm doing wrong?

Best regards and thanks in advance for any hint on this
Andreas

**Comment by ab-tools** [comment]
OK, I figured out how to at least get the example to compile and pushed required changes for that to this pull request here:
https://github.com/OpenKNX/Examples/pull/2

It seems that both `KNX_FLASH_SIZE`/`KNX_FLASH_OFFSET` as well as `OPENKNX_FLASH_SIZE`/`OPENKNX_FLASH_OFFSET` options need to be defined at the moment. Possibly some clean-up is needed here.

And not sure what exactly should go into the 3 versions parameters that are required - just filled them with some dummy info now to get the project at least to compile without errors.

**Comment by thewhobox** [comment]
Hey,

thank you for your feedback.
We made many changes in the past months for our v1 OpenKnx Common Stack.
I hadn`t enough time to update it.

There are some scripts missing in the ini to generate the versions.h for example and the extra_script isnt needed anymore.

I will merge your pull reuqest #2 and add the other changes in a few days.

**Comment by ab-tools** [comment]
Copied, thanks, Mike!

I've added one more example project for merging if you consider this useful, too:
https://github.com/OpenKNX/Examples/pull/3
